# Generated by Django 4.2.7 on 2023-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymassistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="workout",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
