# Generated by Django 4.2.7 on 2023-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymassistant", "0002_alter_workout_end_time_alter_workout_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("calories", models.FloatField()),
                ("protein", models.FloatField()),
                ("fats", models.FloatField()),
                ("carbs", models.FloatField()),
            ],
        ),
    ]
