# Generated by Django 4.2.7 on 2023-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymassistant", "0003_fooditem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="fooditem",
            name="portion_size",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
